name = "TestPackage"
uuid = "1ed0f561-5ce7-4f9d-83cc-219468712614"
authors = ["Matthias Baitsch <matthias.baitsch@me.com>"]
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "0.21, 0.22"
julia = "1.2.1"
